# 使用 Node.js 官方镜像作为构建阶段的基础镜像
FROM node:22 AS build

# 设置工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json
COPY package*.json ./

RUN npm config delete proxy
RUN npm config delete https-proxy

# 安装项目依赖
RUN npm install

# 复制项目文件
COPY . .

# 构建项目
RUN yarn build:dev

# 使用 Nginx 官方镜像作为生产阶段的基础镜像
FROM nginx:alpine

# 复制构建好的静态文件到 Nginx 的默认静态文件目录
COPY --from=build /app/dist /home/demo/voting/dev/dist

# 复制自定义的 Nginx 配置文件
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 暴露 Nginx 默认的端口
EXPOSE 8088

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]
