# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Power-oracle-node-test

on:
  push:
    branches: [ "main" ]
    paths:
      - 'power-oracle-node/*'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'power-oracle-node/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          timeout: 10m
          script: |
            cd ${{ vars.BUILD_PATH }}/power-oracle-node/backend
            sudo sh build.sh
