name: Power-snapshot-test

on:
  push:
    branches: [ "main" ]
    paths:
      - 'power-snapshot/*'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'power-snapshot/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ vars.BUILD_PATH }}/power-snapshot
            sudo sh build.sh

